//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Timer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Timer
    {
        public string Name_Id { get; set; }
        public int SEC { get; set; }
        public int Theme { get; set; }
    }
}
